name: Testing

on:
  pull_request:
    branches:
      - dev

jobs:
  lint:
    name: Lint
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Flake8
        run: python -m pip install flake8

      - name: Run Flake8
        run: |
          python -m flake8 .

  unit_tests:
    name: Unit Tests
    runs-on: windows-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt  # Assuming you have a requirements.txt file for unit tests

      - name: Run unit tests
        run: |
          pytest  # Replace this with the command to run your unit tests

  merge_to_test:
    name: Merge to Test
    runs-on: windows-latest
    needs: unit_tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge to Test Branch
        run: git checkout test && git merge dev && git push origin test
